[Astronomical Constants]                # You may use the constants defined in this section in all subsequent sections, e.g. "scope_left = 1.9 * au". Do not remove any parameters from this section!
g = 6.67430e-11                         # [m^3 / (kg * s^2)] Gravitational constant
au = 1.495978707e11                     # [m]   Astronomical unit
l_sun = 3.828e26                        # [W]   Solar luminosity
r_sun = 6.957e8                         # [m]   Solar radius R⊙
m_sun = 1.98847e30                      # [kg]  Solar mass M⊙
r_jup = 7.1492e7                        # [m]   Jupiter radius
m_jup = 1.8981246e27                    # [kg]  Jupiter mass
r_nep = 2.4622e7                        # [m]   Neptune radius
m_nep = 1.024092e26                     # [kg]  Neptune mass
r_earth = 6.378135e6                    # [m]   Earth radius R⊕
m_earth = 5.9720e24                     # [kg]  Earth mass M⊕
hour = 60 * 60                          # [s]   One hour in seconds
day = hour * 24                         # [s]   One day in seconds
year = day * 365.24219                  # [s]   Approximate length of one tropical Earth year
rad2deg = 57.29577951308232             # Conversion factor: radians to degrees (180 / π)

[Results]                               #
;results_directory = .  # Results are saved in the next available numbered subdirectory.
;result_file = GUI.json           # Simulation results, such as transit times, are saved to this file. Comment out this parameter if you do not need the output file.
verbose = True                          # If False, only error messages are printed to the console. Useful when running MCMC.
unit =  {"mass": "m_jup", "radius": "r_jup", "e": "1", "i": "deg", "P": "d", "a": "AU", "Omega": "deg", "omega": "deg", "pomega": "deg", "L": "deg", "ma": "deg", "ea": "deg", "nu": "deg", "T": "s"}  # Specify the display unit for each parameter in result plots.
scale =  {"mass": 1/m_jup, "radius": 1/r_jup, "e": 1, "i": rad2deg, "P": 1/day, "a": 1/au, "Omega": rad2deg, "omega": rad2deg, "pomega": rad2deg, "L": rad2deg, "ma": rad2deg, "ea": rad2deg, "nu": rad2deg, "T": 1}  # Conversion factors applied to each parameter so that values are displayed in the units specified in parameter unit.

[Simulation]                            #
action = guifit                         # Allowed values: mcmc (MCMC fit), lmfit (least-squares fit), single_run (run one simulation), get_tess_data, process_tess_data, guifit (upcoming feature), results_only (upcoming feature, read existing results and generate reports).
jacobi_masses = True                    # REBOUND parameter. See https://rebound.hanno-rein.de/ipython_examples/OrbitalElements/ .
dt = 75000                              # [s] Time step between simulation iterations. Use a larger value to improve MCMC performance. Use a smaller value for video generation or when accurate transit times are required.
epoch = 2458400                    # [days] Start date of the simulation, typically expressed as a Barycentric Julian Date (TDB).
sim_start =  [2458400]                     # [days] Start times of the intervals for which simulation data are calculated.
sim_end =    [2461046]                     # [days] End times of the intervals for which simulation data are calculated.
;sim_flux_file = ../../curvesimulator.internal/results/Trifon_2026.07.15/sim_flux.csv  # If specified, the simulated flux is saved to this CSV file. The file has the same structure as processed flux data: columns time, flux, and flux_err.

[Fitting]                               #
tt_file = tt_gui.csv                        # Measured transit times. Must contain a column named "tt" with transit midpoints (additional columns are allowed).
eclipsers_names = TOI4504c, TOI4504d    # Only primary transits of these bodies are considered when fitting transit times. Separate body names with commas.
eclipsees_names = TOI4504               # Only transits across these bodies are considered when fitting transit times. Separate body names with commas.

[TOI4504]
body_type = star
color = 0.99, 0.99, 0.99
#           value               lower bound       upper bound        sigma
mass = 0.885 * m_sun,         # 0.84 * m_sun,     0.94 * m_sun,      0.025 * m_sun
radius = 0.92 * r_sun
luminosity = 0.62 * l_sun
limb_darkening_parameter_type = u
limb_darkening_1 = 0.17355
limb_darkening_2 = 0.31489
rv_offset = -2052.686250                # [m/s] Constant shift added to measured RV values to correct for a zero-point difference between the instrument or model and the star’s true line-of-sight velocity. rv_rel = rv + rv_offset
rv_jitter = 99.43006                    # [m/s] Standard deviation of the stellar jitter term, i.e. the typical size of extra RV scatter not caused by planets.


[TOI4504d]
body_type = planet
color =     0.01, 0.99, 0.01
#           value                     lower bound       upper bound        sigma
mass =      2.093560275 * m_jup,     1.0 * m_jup,      5.0 * m_jup,       0.04 * m_jup
radius =    1.085423176 * r_jup,    # 0.2 * r_jup,      4.0 * r_jup,       0.8 * r_jup
e =         0.260171585,             0.0,              0.5,               0.005
i =         88.746161,               88.00,            90.0,              0.01
P =         41.806141 * day,         40 * day,         43 * day,          0.03 * day
Omega =     0.0,                     -10,              10,                2.7
omega =     270.7549465,             170,              370,               4.0
ma =        349.6932931,             250,              450,               8.0


[TOI4504c]
body_type = planet
color =     0.99, 0.99, 0.01
#           value               lower bound       upper bound        sigma
mass =      2.624407891 * m_jup,     1.0 * m_jup,      5.0 * m_jup,       0.025 * m_jup
radius =    1.064014627 * r_jup,    # 0.8 * r_jup,      1.2 * r_jup,       0.15 * r_jup
e =         0.037642491,             0.0,              0.5,               0.0035
i =         89.69211,                89.25,            90.0,              0.2
P =         81.810197 * day,         80.0 * day,       84 * day,          0.07 * day
Omega =     357.820921,             #
omega =     298.5823985,             200,              400,               6.0
ma =        143.1278754,             -30,              330,               6.0
