[Astronomical Constants]                # You may use the constants defined in this section in all subsequent sections, e.g. "scope_left = 1.9 * au". Do not remove any parameters from this section!
g = 6.67430e-11                         # [m^3 / (kg * s^2)] Gravitational constant
au = 1.495978707e11                     # [m]   Astronomical unit
l_sun = 3.828e26                        # [W]   Solar luminosity
r_sun = 6.957e8                         # [m]   Solar radius R⊙
m_sun = 1.98847e30                      # [kg]  Solar mass M⊙
r_jup = 7.1492e7                        # [m]   Jupiter radius
m_jup = 1.8981246e27                    # [kg]  Jupiter mass
r_nep = 2.4622e7                        # [m]   Neptune radius
m_nep = 1.024092e26                     # [kg]  Neptune mass
r_earth = 6.378135e6                    # [m]   Earth radius R⊕
m_earth = 5.9720e24                     # [kg]  Earth mass M⊕
hour = 60 * 60                          # [s]   One hour in seconds
day = hour * 24                         # [s]   One day in seconds
year = day * 365.24219                  # [s]   Approximate length of one tropical Earth year
rad2deg = 57.29577951308232             # Conversion factor: radians to degrees (180 / π)

[Results]                               #
results_directory = .                   # Results are saved in the next available numbered subdirectory.
;transit_precision = 1                   # [s] Simulated TT, T1, etc. are calculated to this precision.
;max_interval_extensions = 5             # Integer: In unstable systems or when using a very large dt, the search for a Transit Time (TT) may have to be extended. If no TT is found within max_interval_extensions * dt of the expected transit interval, the search for that particular TT is aborted.

[Simulation]                            #
action = lmfit                          # Allowed values: mcmc (MCMC fit), lmfit (least-squares fit), single_run (run one simulation), get_tess_data, process_tess_data, guifit (upcoming feature), results_only (upcoming feature, read existing results and generate reports).
jacobi_masses = True                    # REBOUND parameter. See https://rebound.hanno-rein.de/ipython_examples/OrbitalElements/ .
dt = 5000                               # [s] Time step between simulation iterations. Use a larger value to improve MCMC performance. Use a smaller value for video generation or when accurate transit times are required.
start_date = 2460000                    # [days] Start date of the simulation, typically expressed as a Barycentric Julian Date (TDB).
starts =  [2460001.9]                   # [days] Start times of the intervals for which simulation data are calculated.
ends =    [2460003.9]                   # [days] End times of the intervals for which simulation data are calculated.

[Fitting]                               #
lmfit_method = powell                   # LMfit parameter specifying the optimization algorithm. Try powell, nelder, or differential_evolution. See https://lmfit.github.io/lmfit-py/fitting.html .
ls_max_tt_delta = 1e-5               # [days] LMfit stops when the largest difference between a measured TT and its matched simulated TT falls below this value.
flux_file = flux.csv                    # Flux measurement file. Must contain the columns "time" (days), "flux" (normalized flux), and "flux_err" (normalized standard deviation).
;eclipsers_names = InnerPlanet, OuterPlanet  # Only primary transits of these bodies are considered when fitting transit times. Separate body names with commas.
;eclipsees_names = SomeStar              # Only transits across these bodies are considered when fitting transit times. Separate body names with commas.
rv_body = SomeStar                      # Name of the star for which radial velocities were measured.

[SomeStar]                              # All subsequent sections define celestial bodies in the simulation. Section names define the body names. REBOUND supports only plain ASCII characters in body names. When Jacobi coordinates are used, bodies must be ordered from the inside out (e.g., star, inner planet, outer planet).
color = 0.99, 0.99, 0.99                # [1], [1], [1] RGB values used in the animation. All three values must be between 0 and 1.
body_type = star                        # star or planet
mass = 1.0 * m_sun                      # [kg]
radius = 1.0 * r_sun                    # [m]
luminosity = 1.0 * l_sun                # [W]
limb_darkening_parameter_type = u       # limb_darkening_parameter_type = a  # q (Kipping parameters q1, q2), u (quadratic law parameters u1, u2), or a (polynomial coefficients a1, a2; do not provide a0).
limb_darkening_1 = 0.45                 # Limb-darkening coefficient 1.
limb_darkening_2 = 0.23                 # Limb-darkening coefficient 2.

[InnerPlanet]                           #
color = 0.9, 0.9, 0.1                   # [1], [1], [1] RGB values used in the animation. All three values must be between 0 and 1.
body_type = planet                      # star or planet
mass = 3.0 * m_earth                    # [kg]
radius = 1.5 * r_earth, 0.1 * r_earth, 10.0 * r_earth, 0.5 * r_earth  # [m]
e = 0.0                                 # [1] Eccentricity.
i = 89.0                                # [deg] Inclination. 90°: the orbit is viewed edge-on. >90°: the planet moves below and in front of the star, as well as above and behind the star in the edge-on view.
a = 0.1 * au                            # [m] Semi-major axis. Provide P or a.
Omega = 0                               # [deg] Ω: longitude of ascending node. Specify two parameters out of Omega, omega, and pomega.
omega = 0                               # [deg] ω: argument of periapsis/pericenter/periastron. Specify two parameters out of Omega, omega, and pomega.
ma = 6                                  # [deg] Mean anomaly. Specify one parameter out of L, ma, ea, nu, and T.

[OuterPlanet]                           #
color = 0.3, 0.5, 0.99                  # [1], [1], [1] RGB values used in the animation. All three values must be between 0 and 1.
body_type = planet                      # star or planet
mass = 1.0 * m_earth                    # [kg]
radius = 1.0 * r_earth, 0.1 * r_earth, 10.0 * r_earth, 0.5 * r_earth  # [m]
e = 0.045                               # [1] Eccentricity.
i = 90.2                                # [deg] Inclination. 90°: the orbit is viewed edge-on. >90°: the planet moves below and in front of the star, as well as above and behind the star in the edge-on view.
a = 1.0 * au                            # [m] Semi-major axis. Provide P or a.
Omega = 0                               # [deg] Ω: longitude of ascending node. Specify two parameters out of Omega, omega, and pomega.
omega = 0                               # [deg] ω: argument of periapsis/pericenter/periastron. Specify two parameters out of Omega, omega, and pomega.
ma = 82                                 # [deg] Mean anomaly. Specify one parameter out of L, ma, ea, nu, and T.
